### ISSUE TITLE
Aspect ratio slightly off?

### ISSUE THREAD

**Issue by hartwork** [shaochuan/Xiangqi#1]
When I start Xiangqi the pieces look more like eggs rather than circles. So at least in my setup (1920x1080) the aspect ratio is mis-calculated.

**Comment by hartwork** [comment]
Here's a screenshot to demonstrate the aspect ratio I get: 

![flying-generals-issue](https://user-images.githubusercontent.com/1577132/59566721-1ed64900-9064-11e9-8de0-7daf467e87bf.png)

**Comment by shaochuan** [comment]
Thanks for the screenshot!

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…
